title: Python by Puku
tagline: A fun and simple python cource for ages 9 and above
description: >-
  This will be a fun and simple python course for kids. In this course, we will
  learn the basics of python, and how to use them in real-life contexts.
template:
  name: Python-by-Puku
  repo: aaranyak/PythonforPuku-lab-test
  description: 'This is the repository for the python-by-puku course. '
before:
  - type: respond
    with: 01_first-response.md
steps:
  - title: Introduce your program
    actions:
      - type: gate
        left: '%payload.changes[body][to]%'
        operator: ===
        right: print("Welcome to the age app!")
        else:
          - type: respond
            with: 01_try-again.md
      - type: respond
        with: 01_nice-work.md
      - type: respond
        with: 02_activity.md
    description: Tell everybody what your program is about
    event: pull_request.synchronize
  - title: Get the user's input
    actions:
      - type: gate
        left: '%payload.changes[body][to]%'
        operator: ===
        right: age = input("How old are you?")
        else:
          - type: respond
            with: 01_try-again.md
      - type: respond
        with: 02_nice-work.md
      - type: respond
        with: 03_activity.md
    description: Learn how to know what the user want's to say
    event: pull_request.synchronize
  - title: Calculate the date
    description: This is the most important bit of writing a program
    event: pull_request.synchronize
    actions:
      - type: gate
        left: '%payload.changes[body][to]%'
        operator: ===
        right: date = 2020 - age
        else:
          - type: respond
            with: 01_try-again.md
      - type: respond
        with: 03_nice-work.md
      - type: respond
        with: 04_activity.md
  - title: Show the output
    description: Now let's tell the user our output
    event: pull_request.synchronize
    actions:
      - type: gate
        left: '%payload.changes[body][to]%'
        operator: ===
        right: 'print("You were born on", date)'
        else:
          - type: respond
            with: 01_try-again.md
      - type: respond
        with: 04_nice-work.md
      - type: respond
        with: 05_activity.md
  - title: End the course
    description: Finish the course
    event: issue_comment.created
    actions:
      - type: respond
        with: end_message.md
