title: Python by Puku
description: This is a fun and simple python course for young codersaaranyak/new
template:
  repo: python-by-puku-template
  name: python-by-puku
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
